spring:
  application:
   name: securityexam

#  security:
#    user:
#      name: test
#      password: 1234

  datasource:
    url: jdbc:mysql://localhost:3306/securitydb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: spring
    password: spring1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  tomcat:
    threads:
#      max: 200
#      min-spare: 10
      max: 5
      min-spare: 2

logging:
  level:
    org:
      springframework:
        security: trace

jwt:
  accessKey: 12345678901234567890123456789012
  refreshKey: abcdefghijklmnopqrstuvwxzy123456
